### ISSUE TITLE
Chrome下博文显示乱码

### ISSUE THREAD

**Issue by sisibeloved** [Bloss/vuepress-theme-yubisaki#2]
Version: Chrome 66.0.3359.117，Firefox可以正常显示

![image](https://s1.ax1x.com/2018/04/25/C185n0.png)
![image](https://s1.ax1x.com/2018/04/25/C1GCND.png)

**Comment by Bloss** [comment]
@sisibeloved   66.0.3359.117（正式版本） （64 位）我这边也是这个版本号, 显示正常
