### ISSUE TITLE
建议增加评论

### ISSUE THREAD

**Issue by xcsweb** [Bloss/vuepress-theme-yubisaki#5]
建议增加评论

**Comment by Bloss** [comment]
@xcsweb 没有好的实现, 要么自己新建服务, 或者用第三方, 不过目前第三方的没有看到很好用的~, 有推荐吗

**Comment by xcsweb** [comment]
gitment

**Comment by Bloss** [comment]
用 gitalk 搭建了一个评论系统，[评论系统](https://wuwaki.me/yubisaki/usage.html#%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F)

**Comment by hirCodd** [comment]
valine 我用这个弄得，有些bug

**Comment by iofu728** [comment]
用Gitalk搭了一下 可以给大家[参考下](https://wyydsb.xin/javaScript/comment.html)🚶
