### ISSUE TITLE
您好，我想请问一下静态资源文件是否是经过其它的配置呢？

### ISSUE THREAD

**Issue by MeteorOCC** [Bloss/vuepress-theme-yubisaki#6]
我在.vuepress文件夹下放入我的logo，但是我目前没有办法直接引入到您的主题中，请问一下您在引用静态资源的时候是怎么样做的呢~？

**Comment by Bloss** [comment]
你的 logo 需要放入 .vuepress/public 文件夹下, 可以看看官方文档 [https://vuepress.vuejs.org/zh/guide/assets.html#%E5%85%AC%E5%85%B1%E6%96%87%E4%BB%B6](https://vuepress.vuejs.org/zh/guide/assets.html#%E5%85%AC%E5%85%B1%E6%96%87%E4%BB%B6)

**Comment by MeteorOCC** [comment]
您好，我确实是按照官方文档中的操作的。
下面是我的目录结构，内容正常运作 ：）
不使用您的主题的话这个路径是正常的，vuepress的webpack对静态资源的读取都在.vuepress目录下。
感谢回复~！

**Comment by Bloss** [comment]
我没有看见你的目录结构

**Comment by Bloss** [comment]
@MeteorOCC 你好，可以提供一个复现的 repo 吗

**Comment by MeteorOCC** [comment]
已经解决了，我比较早的时候yarn下了Vuepress近期才开始看，public里面的图片默认路径已经不需要详细指定了，经过webpack处理已经是'/'代替了'./public/'
build文档的时候我还发现了一个问题，就是build出来的静态网页没有办法加载样式，查看了一下html文件发现是路径有问题，通过
![image](https://user-images.githubusercontent.com/38990160/41204020-cb8f4cb8-6d11-11e8-8866-51097694d67d.png)
这样配置后就可以读取正确的路径，但是文档反而读取不到了，还在对照官方文档查看webpack配置和自己的路径。
抱歉给您带来麻烦啦:)

**Comment by Bloss** [comment]
All right, amazing
