### ISSUE TITLE
你好，能帮我看下这个报错是怎么回事吗？

### ISSUE THREAD

**Issue by zzkkui** [Bloss/vuepress-theme-yubisaki#8]
![v 0f 24 tj6 u j ri7v](https://user-images.githubusercontent.com/24466870/41325582-ab91d416-6eed-11e8-8727-ca12406bb6d6.png)

这是我的项目目录，从昨天就一直这个错，所以我以为是有依赖没安装，如果有时间麻烦帮我解答下，谢谢！:)
![5d6 y015 rzg3b a qjax](https://user-images.githubusercontent.com/24466870/41325585-b3613b46-6eed-11e8-8ddd-df178a0a2325.png)

**Comment by zzkkui** [comment]
今天我来看了，还有你给我说的，确实不是依赖的问题

**Comment by Bloss** [comment]
方便留下一个复现的 repo 吗

**Comment by zzkkui** [comment]
https://github.com/zzkkui/zzkkuiBlog
麻烦了，:)

**Comment by Bloss** [comment]
https://github.com/zzkkui/zzkkuiBlog/blob/9b26cfb5ae962652560072b4591a187a0fe4c097/docs/.vuepress/config.js#L12-L18
这里去掉就可以正常运行了，原因是这个主题目前采用的导航栏不支持多级目录。文章是以列表的形式展开的，后续会加入目录的功能

**Comment by zzkkui** [comment]
解决了，thanks

**Comment by Bloss** [comment]
👍
